"""Write the plugin manifests from pyproject.toml.

There are two plugin standards and YAAC ships as both. Agent Plugins 1.0.0 (agent-plugins.org, published
2026-08-06) is read by ChatGPT, Codex, Cursor, GitHub Copilot, Kiro and VS Code; Claude Code is not part of it and
keeps its own layout. The two want the same information under different filenames, and the Agent Plugins manifest
sets `additionalProperties: false`, so Claude Code's extra fields cannot simply be added to it -- hence two
manifests rather than one shared file.

They are generated rather than hand-written because they carry a version, and a version in three places drifts at
the first release that forgets one. `tests/test_packaging.py` fails when what is on disk differs from what this
script would write, so a forgotten run is caught by the suite rather than by a user.

Paths are resolved against the repository root rather than the working directory, so it runs from anywhere:

    uv run python .claude/skills/releasing-to-pypi/generate_plugin.py
"""

import json
import tomllib
from pathlib import Path
from typing import Any

# .claude/skills/releasing-to-pypi/generate_plugin.py -> the repository root.
REPO = Path(__file__).resolve().parents[3]
AGENT_PLUGINS = "https://agent-plugins.org/schemas/1.0.0"
GENERATED = "Generated by .claude/skills/releasing-to-pypi/generate_plugin.py -- do not edit by hand."


def project() -> dict[str, Any]:
    return tomllib.loads((REPO / "pyproject.toml").read_text())["project"]


def files() -> dict[str, dict[str, Any]]:
    """Every generated file, as a path relative to the repository root and the object to write there."""
    p = project()
    author = p["authors"][0]
    # uvx resolves the published package at launch, so the plugin carries no copy of the server and never pins a
    # version of it. `type` is required by Agent Plugins and understood by Claude Code.
    server = {"type": "stdio", "command": "uvx", "args": [p["name"]]}

    # Byte-identical today: Claude Code reads `mcpServers` and ignores the `$schema` key that Agent Plugins
    # requires. Kept as two files because only one of the two standards promises to tolerate the other's shape.
    mcp = {"$schema": f"{AGENT_PLUGINS}/mcp.schema.json", "mcpServers": {"yaac": server}}

    return {
        # -- Agent Plugins 1.0.0 --------------------------------------------------
        "plugin/plugin.json": {
            "$schema": f"{AGENT_PLUGINS}/plugin.schema.json",
            "name": "yaac",
            "version": p["version"],
            "description": p["description"],
            "author": {"name": author["name"], "email": author["email"]},
            "homepage": p["urls"]["Homepage"],
            "repository": p["urls"]["Repository"],
            "license": p["license"],
            "keywords": ["mcp", "chat", "messaging", "agents", "zeromq"],
        },
        "plugin/mcp.json": mcp,
        # -- Claude Code ----------------------------------------------------------
        # A different layout for the same facts. `additionalProperties: false` on the Agent Plugins manifest is
        # why this cannot be the same file.
        "plugin/.claude-plugin/plugin.json": {
            "name": "yaac",
            "displayName": "YAAC",
            "version": p["version"],
            "description": p["description"],
            "author": {"name": author["name"], "email": author["email"]},
            "homepage": p["urls"]["Homepage"],
            "repository": p["urls"]["Repository"],
            "license": p["license"],
            "keywords": ["mcp", "chat", "messaging", "agents", "zeromq"],
        },
        "plugin/.mcp.json": mcp,
        # The marketplace lives at the repository root, which is where `/plugin marketplace add owner/repo`
        # looks. One repository, one marketplace, one plugin in it.
        ".claude-plugin/marketplace.json": {
            "name": "yaac",
            "owner": {"name": author["name"], "email": author["email"]},
            "metadata": {"description": "The YAAC radio, as an installable plugin.", "generated": GENERATED},
            "plugins": [
                {
                    "name": "yaac",
                    "source": "./plugin",
                    "description": p["description"],
                    "version": p["version"],
                    "author": {"name": author["name"]},
                }
            ],
        },
    }


def render(content: dict[str, Any]) -> str:
    return json.dumps(content, indent=2) + "\n"


def main() -> None:
    for path, content in files().items():
        target = REPO / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(render(content))
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
