"""Regenerate docs/tools.md from the live tool definitions in yaac.frontend.

Run from the repository root: `uv run python .claude/skills/updating-mcp-tools/generate.py`. Introspects the MCP server
object rather than parsing source, so the output cannot drift from what a client actually sees: the same
registration path that serves tools/list produces the schemas written here.
"""

from pathlib import Path
from typing import Any

from yaac import frontend

GENERATED_MARK = "<!-- Generated by .claude/skills/updating-mcp-tools/generate.py -- do not edit by hand. -->"


def type_of(prop: dict[str, Any]) -> str:
    """Render a JSON-schema property's type compactly, unwrapping the `anyOf` that optional fields produce."""
    if "anyOf" in prop:
        return " | ".join(type_of(alternative) for alternative in prop["anyOf"])
    return str(prop.get("type", "object"))


def tool_section(tool: Any, availability: str) -> list[str]:
    schema = tool.parameters or {}
    properties: dict[str, Any] = schema.get("properties", {})
    required = set(schema.get("required", []))

    lines = [f"## `{tool.name}` — {availability}", "", tool.description.strip(), ""]
    if properties:
        lines += ["| Parameter | Type | Required | Description |", "| --- | --- | --- | --- |"]
        for name, prop in properties.items():
            description = prop.get("description", "")
            lines.append(f"| `{name}` | {type_of(prop)} | {'yes' if name in required else 'no'} | {description} |")
        lines.append("")
    return lines


def main() -> None:
    mcp = frontend.mcp
    on_air_names = {fn.__name__ for fn in frontend.ON_AIR_TOOLS}
    for fn in frontend.ON_AIR_TOOLS:
        # Registration is idempotent for this purpose: the dormant server only lacks these, and registering them
        # here uses the same path `join_channel` uses at runtime, so their schemas come out identical to the wire.
        mcp.add_tool(fn)

    lines = [
        "# MCP tools",
        "",
        GENERATED_MARK,
        "",
        "What a connected client sees. A dormant session lists only the two always-listed tools; the rest are",
        "published on the first `join_channel` and withdrawn when the last channel is left.",
        "",
        "**Server instructions** (sent to the client on connect):",
        "",
        f"> {mcp.instructions}",
        "",
    ]
    tools = mcp._tool_manager.list_tools()
    # Always-listed tools first, then the on-air set; alphabetical within each group so the output is stable.
    for tool in sorted(tools, key=lambda t: (t.name in on_air_names, t.name)):
        availability = "listed only while on air" if tool.name in on_air_names else "always listed"
        lines += tool_section(tool, availability)

    output = Path("docs/tools.md")
    output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {output} ({len(tools)} tools)")


if __name__ == "__main__":
    main()
