"""Regenerate docs/tools.md from the live tool definitions in yaac.frontend.

Run from the repository root: `uv run python .claude/skills/updating-mcp-tools/scripts/generate.py`.

Introspects the MCP server object rather than parsing source, so the output cannot drift from what a client
actually sees: the same registration path that serves tools/list produces the schemas written here.
"""

from pathlib import Path
from typing import Any

from yaac import frontend

GENERATED_MARK = "<!-- Generated by .claude/skills/updating-mcp-tools/scripts/generate.py -- do not edit by hand. -->"


def type_of(prop: dict[str, Any]) -> str:
    """Render a JSON-schema property's type compactly, unwrapping the `anyOf` that optional fields produce."""
    if "anyOf" in prop:
        return " | ".join(type_of(alternative) for alternative in prop["anyOf"])
    return str(prop.get("type", "object"))


def describe_annotations(tool: Any) -> str:
    """The advisory hints, in words. A client uses them to decide what it may call without asking, so a reader of
    these docs should see the same claim the wire makes rather than have to infer it from the description."""
    if (annotations := tool.annotations) is None:
        return ""
    if annotations.read_only_hint:
        return "Read-only: changes nothing, safe to call at any time."
    said = ["not read-only"]
    if annotations.destructive_hint:
        said.append("destructive -- what it does cannot be undone")
    if annotations.idempotent_hint:
        said.append("idempotent -- calling it again changes nothing further")
    return f"{said[0].capitalize()}{''.join(f'; {s}' for s in said[1:])}."


def tool_section(tool: Any, availability: str) -> list[str]:
    schema = tool.parameters or {}
    properties: dict[str, Any] = schema.get("properties", {})
    required = set(schema.get("required", []))

    lines = [f"## `{tool.name}` — {availability}", "", tool.description.strip(), ""]
    if annotations := describe_annotations(tool):
        lines += [f"*{annotations}*", ""]
    if properties:
        lines += ["| Parameter | Type | Required | Description |", "| --- | --- | --- | --- |"]
        for name, prop in properties.items():
            description = prop.get("description", "")
            lines.append(f"| `{name}` | {type_of(prop)} | {'yes' if name in required else 'no'} | {description} |")
        lines.append("")
    return lines


def main() -> None:
    mcp = frontend.mcp
    on_air_names = {fn.__name__ for fn in frontend.ON_AIR_TOOLS}
    # The same call `join_channel` makes at runtime, so schemas and annotations come out identical to the wire.
    frontend.publish_on_air_tools()

    clients = ", ".join(f"`{name}`" for name in sorted(frontend.CLIENTS_THAT_NEVER_RELIST))
    lines = [
        "# MCP tools",
        "",
        GENERATED_MARK,
        "",
        "What a connected client sees. A dormant session lists only the two always-listed tools; the rest are",
        "published on the first `join_channel` and withdrawn when the last channel is left.",
        "",
        "That holds for a client that acts on `notifications/tools/list_changed`. One that does not is given",
        f"every tool at connect instead, since a tool published later would never reach it: {clients}.",
        "",
        "**Server instructions** (sent to the client on connect):",
        "",
        f"> {mcp.instructions}",
        "",
    ]
    # The hook's tool is registered but withheld from every tools/list, so a client never sees it and neither does
    # this reference, which documents what a client is served.
    tools = [tool for tool in mcp._tool_manager.list_tools() if tool.name != frontend.HOOK_TOOL]
    # Always-listed tools first, then the on-air set; alphabetical within each group so the output is stable.
    for tool in sorted(tools, key=lambda t: (t.name in on_air_names, t.name)):
        availability = "listed only while on air" if tool.name in on_air_names else "always listed"
        lines += tool_section(tool, availability)

    output = Path("docs/tools.md")
    output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {output} ({len(tools)} tools)")


if __name__ == "__main__":
    main()
