"""Write every manifest that restates what pyproject.toml already says.

Written for three kinds of reader:

- **Agent Plugins 1.0.0** (agent-plugins.org, published 2026-08-06), read by ChatGPT, Codex, Cursor, GitHub
  Copilot, Kiro and VS Code: `plugin/plugin.json` and `plugin/mcp.json`.
- **Claude Code**, which is not part of that standard and keeps its own layout: `plugin/.claude-plugin/plugin.json`
  and `plugin/.mcp.json`, plus `.claude-plugin/marketplace.json` at the repository root. The two manifests cannot
  be one file: the Agent Plugins schema sets `additionalProperties: false`, so Claude Code's extra fields make it
  invalid.
- **The official MCP registry**: `server.json`.

They are generated rather than written because every one of them restates the version, and a release that
updates all but one ships a package claiming to be something it is not. `tests/test_packaging.py` fails when what
is on disk differs from what this script would write, so a forgotten run is caught by the suite rather than by a
user.

Paths resolve against the repository root rather than the working directory, so it runs from anywhere:

    uv run python .claude/skills/releasing/scripts/generate_manifests.py
"""

import json
import tomllib
from pathlib import Path
from typing import Any

# .claude/skills/releasing/scripts/generate_manifests.py -> the repository root.
REPO = Path(__file__).resolve().parents[4]
AGENT_PLUGINS = "https://agent-plugins.org/schemas/1.0.0"
MCP_REGISTRY_SCHEMA = "https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json"
# GitHub authentication grants this namespace; the registry will not accept a name outside it.
REGISTRY_NAME = "io.github.amyodov/yet-another-agentic-chat"
# The registry caps description at 100 characters where PyPI does not, so it cannot reuse the project's own.
# This is the same sentence without the trailing parenthetical that carries the name.
REGISTRY_DESCRIPTION = "Messaging between concurrent AI coding sessions, across clients, over MCP. Zero infrastructure."
GENERATED = "Generated by .claude/skills/releasing/scripts/generate_manifests.py -- do not edit by hand."


def project() -> dict[str, Any]:
    return tomllib.loads((REPO / "pyproject.toml").read_text(encoding="utf-8"))["project"]


def files() -> dict[str, dict[str, Any]]:
    """Every generated file, as a path relative to the repository root and the object to write there."""
    p = project()
    author = p["authors"][0]
    # uvx resolves the published package at launch, so the plugin carries no copy of the server and never pins a
    # version of it. `type` is required by Agent Plugins and understood by Claude Code.
    server = {"type": "stdio", "command": "uvx", "args": [p["name"]]}

    # Byte-identical today: Claude Code reads `mcpServers` and ignores the `$schema` key that Agent Plugins
    # requires. Kept as two files because only one of the two standards promises to tolerate the other's shape.
    mcp = {"$schema": f"{AGENT_PLUGINS}/mcp.schema.json", "mcpServers": {"yaac": server}}

    return {
        # -- Agent Plugins 1.0.0 --------------------------------------------------
        "plugin/plugin.json": {
            "$schema": f"{AGENT_PLUGINS}/plugin.schema.json",
            "name": "yaac",
            "version": p["version"],
            "description": p["description"],
            "author": {"name": author["name"], "email": author["email"]},
            "homepage": p["urls"]["Homepage"],
            "repository": p["urls"]["Repository"],
            "license": p["license"],
            "keywords": ["mcp", "chat", "messaging", "agents", "zeromq"],
        },
        "plugin/mcp.json": mcp,
        # -- Claude Code ----------------------------------------------------------
        # A different layout for the same facts. `additionalProperties: false` on the Agent Plugins manifest is
        # why this cannot be the same file.
        "plugin/.claude-plugin/plugin.json": {
            "name": "yaac",
            "displayName": "YAAC",
            "version": p["version"],
            "description": p["description"],
            "author": {"name": author["name"], "email": author["email"]},
            "homepage": p["urls"]["Homepage"],
            "repository": p["urls"]["Repository"],
            "license": p["license"],
            "keywords": ["mcp", "chat", "messaging", "agents", "zeromq"],
        },
        "plugin/.mcp.json": mcp,
        # Claude Code only: Agent Plugins 1.0.0 has no hooks. This is what makes the plugin worth having over the
        # plain MCP server -- a session is handed its messages instead of having to remember to ask.
        #
        # `mcp_tool` calls a tool on the server this same plugin installs, which is the process holding the inbox,
        # so there is no second process, no socket and nothing on the wire. The name is the plugin-scoped one that
        # Claude Code requires for a plugin-bundled server.
        #
        # Four events. Three cover every moment a session is doing anything -- before a tool call, when the user
        # speaks, and as a turn ends, the last being the one that reopens a finished turn so the model can act on
        # what arrived. The fourth answers the opposite problem: `SessionStart` fires with `source: compact` after
        # a compaction, and Claude Code adds that event's plain text to the context it starts the next turn with,
        # so it is where a session is handed back the connection ids and secrets the compaction took from it.
        "plugin/hooks/hooks.json": {
            "description": (
                "Hands this session the messages other sessions have sent it, and hands back the connections it "
                "holds when a compaction replaces what it knew. Silent when there is nothing to say."
            ),
            "hooks": {
                event: [
                    {
                        **({"matcher": matcher} if matcher else {}),
                        "hooks": [
                            {
                                "type": "mcp_tool",
                                "server": "plugin:yaac:yaac",
                                "tool": "hook_report",
                                "input": {"event": event, **extra},
                            }
                        ],
                    }
                ]
                # `${tool_name}` is substituted from the hook payload, and lets the delivery stand aside when the
                # tool about to run is check_inbox itself. The `compact` matcher keeps the hand-back to the one
                # SessionStart source that means the model lost what it held: a startup or a resume did not.
                for event, matcher, extra in (
                    ("PreToolUse", None, {"tool_name": "${tool_name}"}),
                    ("UserPromptSubmit", None, {}),
                    ("Stop", None, {}),
                    ("SessionStart", "compact", {}),
                )
            },
        },
        # -- The official MCP registry --------------------------------------------
        # Ownership is proved separately, by the `mcp-name:` marker in the README of the *published* package, so
        # this file can only be submitted once a release carrying that marker is on PyPI.
        "server.json": {
            "$schema": MCP_REGISTRY_SCHEMA,
            "name": REGISTRY_NAME,
            "title": "YAAC",
            "description": REGISTRY_DESCRIPTION,
            "version": p["version"],
            "websiteUrl": p["urls"]["Homepage"],
            "repository": {"url": p["urls"]["Repository"], "source": "github"},
            "packages": [
                {
                    "registryType": "pypi",
                    "identifier": p["name"],
                    "version": p["version"],
                    "transport": {"type": "stdio"},
                }
            ],
        },
        # The marketplace lives at the repository root, which is where `/plugin marketplace add owner/repo`
        # looks. One repository, one marketplace, one plugin in it.
        ".claude-plugin/marketplace.json": {
            "name": "yaac",
            "owner": {"name": author["name"], "email": author["email"]},
            "metadata": {"description": "The YAAC radio, as an installable plugin.", "generated": GENERATED},
            "plugins": [
                {
                    "name": "yaac",
                    "source": "./plugin",
                    "description": p["description"],
                    "version": p["version"],
                    "author": {"name": author["name"]},
                }
            ],
        },
    }


def render(content: dict[str, Any]) -> str:
    return json.dumps(content, indent=2) + "\n"


def main() -> None:
    for path, content in files().items():
        target = REPO / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(render(content), encoding="utf-8")
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
